spring.application.name=recycling-campaign-system

spring.datasource.url=jdbc:postgresql://ep-hidden-salad-afhy6eqq-pooler.c-2.us-west-2.aws.neon.tech/recycling_campaign_system?sslmode=require&channel_binding=requirespring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=neondb_owner
spring.datasource.password=npg_FMwCJ6ozu3eh

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect



#postgresql://neondb_owner:npg_FMwCJ6ozu3eh@ep-hidden-salad-afhy6eqq-pooler.c-2.us-west-2.aws.neon.tech/recycling_campaign_system?sslmode=require&channel_binding=require