spring.application.name=recycling-campaign-system

#spring.datasource.url=${URL}
#spring.datasource.username=${USERNAME}
#spring.datasource.password=${PASSWORD}
#spring.datasource.driverClassName=org.postgresql.Driver


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect


spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.datasource.url=jdbc:h2:mem:creativespacedb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
server.port=8080


#postgresql://neondb_owner:npg_FMwCJ6ozu3eh@ep-hidden-salad-afhy6eqq-pooler.c-2.us-west-2.aws.neon.tech/recycling_campaign_system?sslmode=require&channel_binding=require